name: Daily League Leaders

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 12 * * *' # At 12:05 UTC every day

jobs:
  nba_data_job:
    runs-on: windows-latest
    env:
      NBA_SEASON_START: ${{ vars.NBA_SEASON_START }}
      NBA_SEASON_END: ${{ vars.NBA_SEASON_END }}
    steps:
      - name: Check if in NBA season
        id: check_season
        run: |
          current_date=$(date +%Y%m%d)
          season_start=$(date -d "$NBA_SEASON_START" +%Y%m%d)
          season_end=$(date -d "$NBA_SEASON_END" +%Y%m%d)
          if [[ $current_date -ge $season_start ]] && [[ $current_date -le $season_end ]]; then
            echo "IN_SEASON=true" >> $GITHUB_ENV
          else
            echo "IN_SEASON=false" >> $GITHUB_ENV
          fi

      - name: Off-season stop
        if: ${{ env.IN_SEASON == 'false' }}
        run: |
          echo "Not in NBA season, stopping the action."
          exit 0

      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute League Leaders script
        run: |
          python leagueleaders.py

      - name: Commit Files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Data update (`date +'%Y-%m-%d'`)"
            git push
          else
            echo "No changes to commit."
          fi
