name: Daily League Leaders

on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 12 * * *' # At 05:12 UTC every day

jobs:
  nba_data_job:
    runs-on: ubuntu-latest
    env:
      NBA_SEASON_START: ${{ vars.NBA_SEASON_START }}
      NBA_SEASON_END: ${{ vars.NBA_SEASON_END }}
    steps:
      - name: Check if in NBA season
        id: check_season
        run: |
          current_date=$(date +%Y%m%d)
          season_start=$(date -d "$NBA_SEASON_START" +%Y%m%d)
          season_end=$(date -d "$NBA_SEASON_END" +%Y%m%d)
          if [[ $current_date -ge $season_start ]] && [[ $current_date -le $season_end ]]; then
            echo "IN_SEASON=true" >> $GITHUB_OUTPUT
          else
            echo "IN_SEASON=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repo content
        if: github.event_name == 'push' || (github.event_name == 'schedule' && steps.check_season.outputs.IN_SEASON == 'true')
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute League Leaders script
        run: |
          python leagueleaders.py

      - name: Execute Moreyball script
        run: |
          python moreyball.py

      - name: Commit Files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Data update (`date +'%Y-%m-%d'`)"
          git push
