name: Daily League Leaders

on:
  schedule:
    - cron: '5 12 * * *' # At 05:12 UTC every day

jobs:
  nba_data_job:
    runs-on: ubuntu-latest
    if: ${{ (github.event.schedule == '5 12 * * *') && (format('{0}', github.event.schedule) >= env.NBA_SEASON_START) && (format('{0}', github.event.schedule) <= env.NBA_SEASON_END) }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute League Leaders script
        run: |
          python leagueleaders.py

      - name: Execute Moreyball script
        run: |
          python moreyball.py

      - name: Commit Files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Data update (`date +'%Y-%m-%d'`)"
          git push
